name: Hop

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  linuxRun:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y xorg xvfb x11-apps imagemagick

      - name: launch and screenshot
        run: |
          export DISPLAY=:99
          sudo Xvfb :99 -screen 0 1024x768x8 &
          xwd -root -silent | convert xwd:- png:screenshot.png
          
      
    

